
spring:
  datasource:
    url : jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration: # 등록을 하는 과정
          naver:
            client-id: xNXW46RbHh0bz4ZQl5xg
            client-secret: l0uSGzHhbN
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
        provider:
          naver:
            authorization-url: https://nid.naver.com/oauth2.0/authorize # redirect를 어디로 보낼지
            token-uri: https://nid.naver.com/oauth2/token # 나중에 설명
            user-info-uri: https://openapi.naver.com/v1/nid/me # resource 서버 (사용자의 정보를 요청하기 위한 경로)
            user-name-attribute: response
            # 요청을 보내면 사용자에 대한 정보가 응답으로 돌아오는데,
            # 돌려받은 데이터 중에서 어떤 것을 사용자의 이름으로 사용할 것인지

            