spring:
  profiles:
    active: test
logging:
  level:
    root: debug
custom:
  property:
    single: custom-property
    comlist: comma,sparated,list,to,value
    ncp:
      id: api-id
      key: api-key
      url: https://ncp.com/



#spring:
#  config:
#    active:
#      on-profile: local
#  datasource:
#    driver-class0-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/demo_jpa_schema
#    username: demo_jpa
#    password: tmddlf0515!@
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#

#---
#spring:
#  config:
#    active:
#      on-profile: docker
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.17.0.1:3306/demo_jpa_schema
#    username: demo_jpa
#    password: tmddlf0515!@
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#---
#spring:
#  config:
#    active:
#      on-profile: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://aws-host.ap.north-2.com.rds:3306/demo_jpa_schema
#    username: demo_jpa
#    password: tmddlf0515!@
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
