spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo-schema
    username: demo_user
    password: Qkrwngud12@

mybatis:
  mapper-locations: "classpath:mybatis/mappers/*.yml"
  configuration:
    map-underscore-to-camel-case: true