spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TestBoard?useSSL=false&serverTimezone=UTC
    username: TestBoardDB-user
    password: password1

jpa:
  database: mysql
  show-sql: true
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    format_sql: true
