spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    # 안되는거 목록
    # 일반 실행 -> yml파일 실행
    # java -jar build/libs/jpa-0.0.1-SNAPSHOT.jar
    # java -Dspring.profiles.active
    # java -Dspring.profiles.active=local -jar build/livs/jpa-0.0.1-SNAPSHOT.jar =>
    # 오류: 기본 클래스 .profiles.active=local을(를) 찾거나 로드할 수 없습니다.
    # 원인:
    #  java.lang.ClassNotFoundException: /profiles/active=local
    # expert SPRING_PROFILES_ACTIVE=local => 오류
    # echo $SPRING_PROFILES_ACTIVE => 아무 결과 x
    # SPRING_PROFILES_ACTIVE=test java -jar build/libs/jpa-0.0.1-SNAPSHOT.jar